server.error.include-binding-errors: ALWAYS
spring:
  output.ansi.enabled: ALWAYS
  h2:
    console:
      enabled: false
  datasource:
    url: jdbc:h2:mem:./spring-boot-h2-db
  jpa.hibernate.ddl-auto: update
task.template.allowMultipleTasksFromTemplate: false

